### ISSUE TITLE
Can't change slice view

### ISSUE THREAD

**Issue by akeshavan** [akeshavan/neurobrain#1]
For some reason, I'm not able to get this thing to show any slice orientation other than axial. @vsoch want to take a look?

**Comment by vsoch** [comment]
Definitely! Will look later today I’m at doctor appointment right now! 🏥

**Comment by vsoch** [comment]
hey @akeshavan I did a review of a bunch of viewers (or APIs) N=1, and with ami, I was a bit underwhelmed. At least, there are other bases I think to start from. Have you looked at the Dicom Web Viewer? https://github.com/ivmartel/dwv It has the things that you like (install from package manager, API, examples) but seems to be a lot more than AMI. If a little more bare bones is ok, https://github.com/cornerstonejs/cornerstone also seems to be very rich with features. The biggest difference, actually, was how slow rendering was using three.js, even for an equivalent dicom series (three.js vs. just loading the series as 2d to scroll through). But I do recognize that the use cases are likely different (AMI with three.js would be good for one volume rendering, and the others for a general medical viewer for clinical applications). Anyway I'm going to discuss my review and then I can get back to you about which of the bases might have some feet!

**Comment by akeshavan** [comment]
Agreed that this rendering is slow! It seems like dwv doesn't work for niftis, but cornerstone might, so its definitely worth looking into. 

That being said, I'm closing this issue because I just pushed changes to get all views: 

<img width="618" alt="screen shot 2018-08-28 at 9 10 02 am" src="https://user-images.githubusercontent.com/972008/44736743-d59d1480-aaa4-11e8-8b90-6643244abb61.png">

but lets open another issue to discuss alternatives?
